# Generated by Django 3.1.7 on 2021-03-07 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210307_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(default='Тема')),
                ('text', models.TextField(default='Текст')),
                ('page', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.pageusers')),
            ],
        ),
    ]
