# Generated by Django 3.1.7 on 2021-05-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210505_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageusers',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds'),
        ),
        migrations.AlterField(
            model_name='pageusers',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
