# Generated by Django 3.1.7 on 2021-05-08 18:38

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20210508_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageusers',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=contact.models.photo_path),
        ),
        migrations.AlterField(
            model_name='pageusers',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=contact.models.photo_path),
        ),
    ]
