# Generated by Django 3.1.7 on 2021-05-08 18:59

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20210508_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageusers',
            name='logo',
            field=models.ImageField(blank=True, default='default-user.jpeg', null=True, upload_to=contact.models.photo_path),
        ),
    ]
