# Generated by Django 3.1.7 on 2021-05-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageusers',
            name='logo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
