# Generated by Django 3.1.7 on 2021-06-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_chatroom_publicroomchatmessage_roomchatmessagemanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='users',
        ),
        migrations.RemoveField(
            model_name='publicroomchatmessage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='publicroomchatmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='RoomChatMessageManager',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='PublicRoomChatMessage',
        ),
    ]
