# Generated by Django 3.1.7 on 2021-05-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20210503_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageusers',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
