# Generated by Django 3.1.7 on 2021-05-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20210503_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageusers',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
