# Generated by Django 3.1.7 on 2021-05-04 19:31

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_pageusers_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageusers',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='logos'),
        ),
    ]
