# Generated by Django 3.1.7 on 2021-06-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_imagesuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageusers',
            name='imgs',
            field=models.ManyToManyField(to='contact.ImagesUser'),
        ),
    ]
