# Generated by Django 3.1.7 on 2021-06-13 12:25

import contact.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0017_pageusers_imgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='noname', max_length=200)),
                ('logo', models.ImageField(upload_to=contact.models.photo_path)),
                ('desc', models.TextField(default='')),
                ('background', models.ImageField(upload_to=contact.models.photo_path)),
                ('admins', models.ManyToManyField(blank=True, related_name='admins', to=settings.AUTH_USER_MODEL)),
                ('imgs', models.ManyToManyField(blank=True, to='contact.ImagesUser')),
                ('moders', models.ManyToManyField(blank=True, related_name='moders', to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(blank=True, to='contact.Post')),
            ],
        ),
    ]
