# Generated by Django 3.1.7 on 2021-06-13 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0019_public_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='type_public',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.types'),
        ),
    ]
