# Generated by Django 3.1.7 on 2021-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_public_type_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageusers',
            name='publics',
            field=models.ManyToManyField(to='contact.Public'),
        ),
    ]
