# Generated by Django 3.1.7 on 2021-06-13 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0021_pageusers_publics'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='black_list',
            field=models.ManyToManyField(related_name='black_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
