# Generated by Django 3.1.7 on 2021-06-21 20:21

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0022_public_black_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageusers',
            name='logo',
            field=models.ImageField(blank=True, default='user-default.jpeg', null=True, upload_to=contact.models.photo_path),
        ),
    ]
