from django.contrib import admin
from django.urls import path, include
from contact.views import (start_page,
                           register,
                           login_user,
                           logout_user,
                           page,
                           home,
                           settings_page,
                           oauth_page,
                           name_surname_page,
                           search_func,
                           follow_user,
                           unfollow_user,
                           user_follows,
                           testindex,
                           room,
                           create_or_go_room,
                           followers_user,
                           news_page,
                           all_photos_user,
                           del_img_user,
                           rooms_page,
                           add_comment,
                           public_page,
                           del_post,
                           public_settings,
                           public_subscribers,
                           set_admin,
                           set_moder,
                           public_imgs_page,
                           add_to_blacklist,
                           del_from_blacklist,
                           sub_to_public,
                           publics_user,
                           create_public)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('', start_page, name='start_page'),
    path('register/', register, name='register_page'),
    path('login/', login_user, name='login_page'),
    path('logout/', logout_user, name='logout_page'),
    path('<int:pid>/', page, name='page'),
    path('settings/', settings_page, name='settings_page'),
    path('home/', home, name='home'),
    path('oauth/', oauth_page, name='oauth_page'),
    path('next_step/', name_surname_page, name='name_surname_page'),
    path('search/', search_func, name='search_page'),
    path('follow_user/', follow_user, name='follow_user'),
    path('unfollow_user/', unfollow_user, name='unfollow_user'),
    path('user_follows/<int:user_id>/', user_follows, name='user_follows_page'),
    path('testindex/', testindex, name='testindex'),
    path('room/<str:room_name>/', room, name='room'),
    path('create_or_go_room/<int:another_user>/', create_or_go_room, name='create_or_go_room'),
    path('followers/<int:user_id>/', followers_user, name='followers_user'),
    path('news/', news_page, name='news_page'),
    path('all_photos/<pageid>/', all_photos_user, name='all_photos'),
    path('del_img/', del_img_user, name='del_img'),
    path('rooms/', rooms_page, name='rooms'),
    path('add_comment/', add_comment, name='add_comment'),
    path('public/<int:pib>/', public_page, name='public_page'),
    path('del_post/', del_post, name='del_post'),
    path('public/<int:pib>/settings/', public_settings, name='public_settings'),
    path('public/<int:pib>/subscribers/', public_subscribers, name='public_subscribers'),
    path('set_admin/', set_admin, name='set_admin'),
    path('set_moder/', set_moder, name='set_moder'),
    path('public/<int:pib>/imgs/', public_imgs_page, name='public_imgs'),
    path('add_to_bl/', add_to_blacklist, name='add_to_bl'),
    path('del_from_bl/', del_from_blacklist, name='del_from_bl'),
    path('sub_to_public/', sub_to_public, name='sub_to_public'),
    path('publics/<int:user_id>/', publics_user, name='pubs_user'),
    path('create_pub/', create_public, name='create_public')

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
